# Generated by Django 3.1 on 2021-03-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend', models.IntegerField(blank=True, null=True, verbose_name='支出')),
            ],
            options={
                'db_table': '支出',
            },
        ),
        migrations.CreateModel(
            name='MonthlyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syogaku', models.IntegerField(blank=True, default=-54000, null=True, verbose_name='奨学')),
                ('subscription', models.IntegerField(blank=True, default=-540, null=True, verbose_name='サブスク')),
            ],
            options={
                'db_table': '月額',
            },
        ),
        migrations.CreateModel(
            name='SyunyuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syunyu', models.IntegerField(blank=True, null=True, verbose_name='収入')),
            ],
            options={
                'db_table': '収入',
            },
        ),
        migrations.CreateModel(
            name='ZandakaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zandaka', models.IntegerField(blank=True, null=True, verbose_name='残高')),
            ],
            options={
                'db_table': '残高',
            },
        ),
    ]
