# Generated by Django 3.1 on 2021-03-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyuyo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zandakamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zandakamodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='expensemodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='monthlymodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='syunyumodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='zandakamodel',
            table=None,
        ),
    ]
