# Generated by Django 3.1 on 2021-03-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyuyo', '0002_auto_20210307_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
