# Generated by Django 3.1 on 2021-03-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyuyo', '0003_monthlymodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymodel',
            name='tital',
            field=models.IntegerField(blank=True, null=True, verbose_name='月額累計'),
        ),
        migrations.AlterField(
            model_name='monthlymodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
