# Generated by Django 3.1 on 2021-03-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyuyo', '0004_auto_20210307_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlymodel',
            old_name='tital',
            new_name='total',
        ),
    ]
